[package]
name = "soulseek-rs-lib"
version = "0.1.0"
edition = "2024"
description = "Library for Soulseek protocol implementation in Rust"
keywords = ["soulseek", "p2p", "protocol", "file-sharing"]
categories = ["network-programming"]

[lib]
name = "soulseek_rs"
path = "src/lib.rs"

[dependencies]
